### PR TITLE
feat: upgrade to empirica latest

### PR DESCRIPTION
**Pull request by npaton**

### CODE REVIEW

**Comment by JamesPHoughton** [comment]
- Tests are passing locally with the `docker-compose-dev.yml` container
- There is an issue related to building the container in github actions: https://github.com/Watts-Lab/deliberation-empirica/actions/runs/3085416333/jobs/4988679363#step:3:224, this is also using the dev container, so I'm surprised that it is giving issues. 
@npaton - any ideas?

**Comment by npaton** [comment]
I couldn't figure out the Cypress thing.

I found some issue alluding to this being a problem others are having, though there is no clear fix from what I can see:
- https://github.com/cypress-io/github-action/issues/235
- https://github.com/cypress-io/github-action/issues/286
- https://github.com/shapeshift/web/issues/1325

Maybe an update to Cypress could help. I don't, I have very little experience with Cypress. I don't quite understand how this whole setup works. There are none of the container logs (not in these failing runs, not in the previous working runs).

**Comment by JamesPHoughton** [comment]
Enabled GH action debug logging, lets try again and see if we get more useful info

**Review by JamesPHoughton — APPROVED** [review]

**Comment by JamesPHoughton** [comment]
Tests are occasionally failing because of flake in admin console accessing. Addressing this in a future PR.

**Pull request merged**
