### PR TITLE
Update to trigger on pr approve

### PR DESCRIPTION
**Pull request by Alan-Qiao**
I hope this works

### CODE REVIEW

**Review by JamesPHoughton — APPROVED** [review]
I wonder it it will run on this approval?

**Comment by Alan-Qiao** [comment]
It did run, but got Error 128, cannot push because in detached state. Trying to figure out what to do

**Comment by JamesPHoughton** [comment]
Another thing we could do is make it part of the build process - ie, edit
the index.html as a Command in the dockerfile.

**Comment by Alan-Qiao** [comment]
Not sure why this is the case, but if I run on push, it works fine. I managed to change the version, and it only triggers the workflow once

**Review by JamesPHoughton — APPROVED** [review]

**Comment by JamesPHoughton** [comment]
Looks like the action had an error: https://github.com/Watts-Lab/deliberation-empirica/runs/7580841731?check_suite_focus=true

**Comment by Alan-Qiao** [comment]
I think what happens is that on pull request approve always fails. but it works if I do on commit. So the solution is to remove the on pull_request_approve trigger.

**Comment by JamesPHoughton** [comment]
@Alan-Qiao why aren't the cypress tests run on this branch?

**Comment by JamesPHoughton** [comment]
maybe they are... https://github.com/Watts-Lab/deliberation-empirica/runs/7617390114?check_suite_focus=true just not showing up in the pending checks...

**Pull request merged**
