### PR TITLE
Bug fix/display exit survey

### PR DESCRIPTION
**Pull request by Alan-Qiao**
Could not push to branch protected by review so made a new pull request.
- Fixed incorrect syntax on imports for SurveyWrapper.jsx and ExampleExitSurvey.jsx
- Added survey-react to client dependencies
- Tested survey on simple experiment batch
- Fixed Merge Conflicts with Docker Update

### CODE REVIEW

**Comment by Alan-Qiao** [comment]
#13

**Review by JamesPHoughton — APPROVED** [review]

**Comment by JamesPHoughton** [comment]
@Alan-Qiao go ahead and merge!

**Comment by JamesPHoughton** [comment]
The best way to solve this conflict is probably to merge main into your branch, and then you should be able to merge.

**Comment by Alan-Qiao** [comment]
Did not pass UI test because page displays request for microphone/camera permissions instead of jitsu screen. This merge does not deal with any of that.

**Pull request merged**
